### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by efaryna** [HodofHod/Userscripts#8]
I've got chrome  50.0.2661.102 m with Tampermonkey installed. I installed the lesson review script and Tampermonkey says the script is enabled and on, but I don't see any change anywhere on the DL website. Is there supposed to be a new button somewhere or something?

**Comment by HodofHod** [comment]
I haven't had time to maintain this userscript in a while. It would seem that, in the meantime, changes to Duolingo have broken the script. I'll add a note to this repo to reflect that.
