### ISSUE TITLE
Problem with the question mark punctuation in Spanish

### ISSUE THREAD

**Issue by jaybh** [HodofHod/Userscripts#9]
Great script, absolutely love it.

When I am trying to enter the reversed question mark at the beginning of an interrogative, "Shift+?+Alt" works, but "Alt+Shift+?" does not.

Is this a known issue/behaviour, or a tiny niggle worth fixing ?

**Comment by HodofHod** [comment]
Done. Give that a try, see if it works.

**Comment by jaybh** [comment]
Thanks. I think this has been fixed. Appreciate it man. Once again, love your script !
